tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  server_type:
    derived_from: tosca.nodes.SoftwareComponent
    interfaces:
      Standard:
        operations:
          create: 
            implementation: playbooks/create.yaml

            inputs:
              ctr_json_url:
                description: URL for getting the json description of the controller
                type: string
                default: "http://0.0.0.0:8080/ipfs/QmXEh2BQ8giM52cWesEbWLtgmyTDv3d7c6ziDngkpTsjVk"

          delete: 
            implementation: playbooks/delete.yaml

        
topology_template:

  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    server:
      type: server_type
      requirements:
        - host: my-workstation
